services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.docker  
    volumes:
    - /app                     
    command: python -m app.main       

volumes:
  pgdata: