services:
  db:
    image: postgres:latest
    env_file: .env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.docker  
    volumes:
      - /app                     
    command: python -m app.main       

volumes:
  pgdata: